all:
	gcc -Iinclude/ src/main.c src/line.c src/point.c src/color.c -o line.exe -lmingw32 -lSDL2main -lSDL2

linux:
	gcc -Iinclude/ src/main.c src/line.c src/point.c src/color.c -o line -lSDL2main -lSDL2

